### ISSUE TITLE
目前不能用了么？

### ISSUE THREAD

**Issue by jymot** [forkgood/easyhosts#1]
如题

**Comment by forkgood** [comment]
Google 近段时间原作者更新的IP是失效的，目前的216.58.220.192正常访问，请重试

**Comment by jymot** [comment]
刚刚测试貌似是不可以的。

**Comment by forkgood** [comment]
最近Google IP较不稳定，可再尝试Ping 216.58.200.33，如果连通，可以将原有相关记录批量更换为216.58.200.33

**Comment by jymot** [comment]
这个可以`ping`通，但是访问不了。

**Comment by forkgood** [comment]
项目已进行人工干预，在此之前本项目的规则均来源于上游项目的Hosts规则，期待持续关注并反馈可用性。
